# Generated by Django 3.0.14 on 2024-04-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_power', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('clock_speed', models.IntegerField()),
                ('dual_sim', models.IntegerField()),
                ('fc', models.IntegerField()),
                ('four_g', models.IntegerField()),
                ('int_memory', models.IntegerField()),
                ('m_dep', models.IntegerField()),
                ('mobile_wt', models.IntegerField()),
                ('n_cores', models.IntegerField()),
                ('pc', models.IntegerField()),
                ('px_height', models.IntegerField()),
                ('px_width', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('sc_h', models.IntegerField()),
                ('sc_w', models.IntegerField()),
                ('talk_time', models.IntegerField()),
                ('three_g', models.IntegerField()),
                ('touch_screen', models.IntegerField()),
                ('wifi', models.IntegerField()),
                ('price_range', models.IntegerField()),
            ],
        ),
    ]
