# Generated by Django 3.0.14 on 2024-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restdevicespriceclassification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='price_range',
        ),
        migrations.AlterField(
            model_name='device',
            name='battery_power',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='blue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='clock_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='dual_sim',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='mobile_wt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='n_cores',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='pc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='px_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='px_width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='ram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='sc_h',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='sc_w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='talk_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='three_g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='touch_screen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='wifi',
            field=models.FloatField(),
        ),
    ]
